name: blood_donation
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    # Map Styles
    - assets/map/
    # Profiles
    - assets/images/profile/
    # Shopping
    - assets/images/apps/shopping/
    - assets/images/apps/shopping/product/
    - assets/images/apps/shopping/offer/
    - assets/images/apps/shopping/camera/
    - assets/images/apps/shopping/vector/
    # Shopping2
    - assets/images/apps/shopping2/icons/
    - assets/images/apps/shopping2/images/
    # Brand
    - assets/brand/
    # Hotel
    - assets/images/apps/hotel/
    # Places
    - assets/images/place/
    # Music
    - assets/images/apps/music/
    # Food
    - assets/images/apps/food/
    # Estate
    - assets/images/apps/estate/
    # Course
    - assets/images/apps/course/
    # Chat
    - assets/images/apps/chat/
    # Social
    - assets/images/apps/social/
    # Other
    - assets/images/all/
    # Event
    - assets/images/apps/event/
    # Avatars
    - assets/images/profile/
    ###################---------------------- Full Apps -------------------------#################
    ## Animations
    # Shopping
    # Shopping Manager
    - assets/full_apps/animations/shopping/data/
    - assets/images/full_apps/shopping/
    - assets/images/full_apps/shopping/icons/
    - assets/full_apps/animations/shopping_manager/data/
    # Rental Service
    - assets/full_apps/animations/rental_service/data/
    - assets/images/full_apps/rental_service/images/
    - assets/images/full_apps/rental_service/icons/
    # NFT
    - assets/full_apps/animations/nft/data/
    - assets/images/full_apps/nft/images/
    - assets/images/full_apps/nft/icons/
    ## m3
    # Cookify
    - assets/full_apps/m3/cookify/data/
    # Dating
    - assets/full_apps/m3/dating/data/
    # Estate
    - assets/full_apps/m3/estate/data/
    # HomeMade
    - assets/full_apps/m3/homemade/data/
    # Learning
    - assets/full_apps/m3/learning/data/
    # Plant
    - assets/images/full_apps/plant/images/
    - assets/full_apps/animations/plant/data/
    ## Other
    # Dating
    - assets/full_apps/others/dating/data/
    # Fitness
    - assets/images/apps/fitness/images/
    - assets/full_apps/others/fitness/data/
    # HomeMade
    - assets/full_apps/others/homemade/data/
    # Muvi
    - assets/full_apps/others/muvi/data/
    ###################---------------------- Custom Apps -------------------------#################
    # Grocery
    - assets/images/apps/grocery/
    # Homemade
    - assets/images/apps/homemade/
    - assets/images/apps/homemade/products/
    - assets/images/apps/homemade/category/
    - assets/images/apps/homemade/shop/
    # Dating
    - assets/images/apps/dating/
    # Muvi
    - assets/images/apps/muvi/
    # CustomApps
    - assets/images/apps/cookify/
    - assets/images/apps/grocery/
    - assets/images/apps/medicare/
    # Learning  (Material Design 3)
    - assets/images/apps/learning/images/
    - assets/images/apps/learning/icons/
    # Illustration
    - assets/illustration/food/
    - assets/illustration/shopping/
    - assets/illustration/hotel/
    - assets/illustration/music/
    # Month backgrounds
    - assets/images/month_background/
    # Languages
    - assets/lang/
    # Icons
    - assets/icons/
    # Rive Animations
    - assets/animations/rive/
    # Other
    - assets/other/