// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDrj4qbFr6_o9DX-PYBlT758diM_rW52Q',
    appId: '1:796201942998:web:bf266ef98c192cccf46e77',
    messagingSenderId: '796201942998',
    projectId: 'blood-donation-d5002',
    authDomain: 'blood-donation-d5002.firebaseapp.com',
    storageBucket: 'blood-donation-d5002.appspot.com',
    measurementId: 'G-0LEE5TNJRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jNlQRsFr739O3mmbaa0gWtsmTjvnJSo',
    appId: '1:796201942998:android:812c8a7ca8ec72e7f46e77',
    messagingSenderId: '796201942998',
    projectId: 'blood-donation-d5002',
    storageBucket: 'blood-donation-d5002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9AiqE5yJB1kst97lgyNl0ScnKuv8Y4E',
    appId: '1:796201942998:ios:382ce17f3a71a6ddf46e77',
    messagingSenderId: '796201942998',
    projectId: 'blood-donation-d5002',
    storageBucket: 'blood-donation-d5002.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR9AiqE5yJB1kst97lgyNl0ScnKuv8Y4E',
    appId: '1:796201942998:ios:382ce17f3a71a6ddf46e77',
    messagingSenderId: '796201942998',
    projectId: 'blood-donation-d5002',
    storageBucket: 'blood-donation-d5002.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDrj4qbFr6_o9DX-PYBlT758diM_rW52Q',
    appId: '1:796201942998:web:5128b4098f5b8257f46e77',
    messagingSenderId: '796201942998',
    projectId: 'blood-donation-d5002',
    authDomain: 'blood-donation-d5002.firebaseapp.com',
    storageBucket: 'blood-donation-d5002.appspot.com',
    measurementId: 'G-18ZYXBFGY1',
  );
}
